#!/usr/bin/env bash

if [[ -s "/home/pirai/.rvm/environments/ruby-1.9.2-p180" ]] ; then
  source "/home/pirai/.rvm/environments/ruby-1.9.2-p180"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/pirai/.rvm/environments/ruby-1.9.2-p180'" >&2
  exit 1
fi
  